global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'alert-correlator'

receivers:
- name: 'alert-correlator'
  webhook_configs:
  - url: 'http://alert-correlator:5000/alert'
    send_resolved: true