services:
  alert-correlator:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: alert-correlator
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ../logs:/var/log
      - ../backend:/app/backend
      - ../frontend:/app/frontend
    depends_on:
      - prometheus
      - loki

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ../config/monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--web.external-url=http://localhost:9093'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ../config/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - ../grafana/provisioning:/etc/grafana/provisioning
      - ../grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - loki

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ../config/logging/loki-config.yaml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    user: root
    volumes:
      - ../logs:/var/log
      - ../config/logging/promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - alert-correlator

  runbooks:
    build:
      context: ..
      dockerfile: docker/Dockerfile.runbooks
    container_name: runbooks
    ports:
      - "3002:3000"
    volumes:
      - ../runbooks:/app/runbooks
